title: Alex Jurado # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate in economics with experience in finances and accounting turned data analyst. Currently   learning data science and how to automatise everything and anything with code, as well as identifying patterns and trends in consumer/data behaviour. I also have a strong interest in sociology and cultural tendencies.
  Recently been growing my knowledge in machine learning and deep learning specially natural language processing (NLP) and keeping up with the latest models. I find the world where human language and machine language meet is specially interesting.
 
  Worked teaching english and in accounting with a focus in real state, this provided not only with the patience to endure teaching teenagers in a classroom but also some valuable organisational skills and working with large amounts of data, as well as finding areas where to cut costs when required based on judgement. 

  Looking for a job that will allow me to grow sharpen and develop my skills in the data science and analysis world.

  Also looking to work on projects related to machine learning, web scraping and data visualisation, especially NLP and dash. So if you want to collaborate please reach out!  <br><br>
  
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
